### ISSUE TITLE
MENU - Language Display

### ISSUE THREAD

**Issue by odamour** [Zenika/zenika.ca#265]

**Comment by odamour** [comment]
Contrast of language is a bit low on unselect value
![screen shot 2019-02-05 at 1 46 43 pm](https://user-images.githubusercontent.com/13982550/52296598-ccb24800-294c-11e9-9535-a321cf2dd3ea.png)

- Remove background to just display in red the not selected language
ex: ENGLISH or FRANÇAIS

**Comment by mfrachet** [comment]
Seems weird to be since the language is not part of the menu (which doesn't make sense):

<img width="1440" alt="screen shot 2019-02-06 at 9 58 32 am" src="https://user-images.githubusercontent.com/3874873/52350121-de9bf580-29f5-11e9-9a08-d3c1d6bcf44b.png">

ping @odamour
