### ISSUE TITLE
CONTACT

### ISSUE THREAD

**Issue by odamour** [Zenika/zenika.ca#268]
- Rename CONTACT with :
FR : CONTACTEZ-NOUS
EN : CONTACT US

- Add a facultatif Phone Number field
- Reduce the size of the bloc to fit the form
- Dropdown is too long, perhaps split with a first level :
Formation / Service / Autres
If Formation, then allow a select with the dropdown

**Comment by lbonanni** [comment]
"* Dropdown is too long, perhaps split with a first level :
  Formation / Service / Autres
  If Formation, then allow a select with the dropdown"

@odamour it will not change the dropdown length 🤔
