### ISSUE TITLE
SEO - All Pages

### ISSUE THREAD

**Issue by odamour** [Zenika/zenika.ca#336]
FRANCAIS

ACCUEIL
Cabinet d'innovation technologique, organisationnelle et managériale - Zenika Canada

Zenika est un cabinet spécialisé dans la transformation numérique, organisationnelle et managériale des entreprises. Zenika fait le lien entre le monde organique et le monde numérique et se positionne comme un One Stop Shop pour ses clients.

ZENIKA
Zenika - A propos de notre groupe international | Cabinet de services en innovation à Montréal

Zenika accompagne les entreprises dans leur transformation technologique, organisationnelle et managériale. Anticiper les évolutions est le coeur de notre activité, et comprendre les besoins de l’écosystème de demain se fait dès aujourd’hui. Notre volonté est de créer le lien entre le monde organique et le monde numérique et d’être un «One Stop Shop» pour nos clients.

CULTURE
Culture Zenika - Animes par la passion | Cabinet de services en innovation à Montréal

La culture Zenika vise la creation d’un environnement favorable au regroupement de collaborateurs compétents, animés par la passion, créatifs et ayant le souci de la qualité. Ceci passe aussi par le souhait de transmettre, former et partager  avec des meetup, matinale, conférences et lunch and learn.

FORMATIONS
Formations Open Source, Craft et Agiles par des experts | Zenika Montréal

Découvrez nos formations aux dernières technologies open-source dans les domaines Java, Spring, Big Data & NoSQL, Craftmanship, DevOps, Web; Managériale avec Agilité (Scrum, Kanban), mngt3.0, Design Thinking, Design Sprint et IoT(objets connectés)

**Comment by odamour** [comment]
ENGLISH

HOME
Technology, Organizational and Managerial Innovation Firm - Zenika Canada

Zenika is a firm specialized in the digital, organizational and managerial transformation of companies. Zenika made the connection between the organic world and the digital world and positions itself as a one stop shop for its customers.

Zenika
Zenika - About our international group | Innovation Services Firm in Montreal

Zenika supports companies in their technological, organizational and managerial transformation. Anticipate changes is the heart of our business, and understand the needs of the ecosystem of tomorrow is today. Our desire is to create the link between the organic world and the digital world and to be a "One Stop Shop" for our customers.

CULTURE
Zenika Culture - Led by Passion | Innovation Services Firm in Montreal

The Zenika culture aims to create an environment conducive to the grouping of competent, passionate, creative and quality-conscious employees. This also means the desire to transmit, educate and share through meetup, morning, lectures and lunch and learn.

TRAINING
Open Source, Craft and Agile Training by Experts | Zenika Montreal

Discover our training in the latest open-source technologies in Java, Spring, Big Data & NoSQL, Craftmanship, DevOps, Web; Manager with Agility (Scrum, Kanban), mngt3.0, Design Thinking, Design Sprint and IoT (connected objects)

**Comment by mfrachet** [comment]
✅
