### ISSUE TITLE
Texte - Page Culture

### ISSUE THREAD

**Issue by odamour** [Zenika/zenika.ca#338]
Texte corrige sans faute : 
Zenika a créé un environnement favorable au regroupement de collaborateurs compétents, animés par la passion, créatifs et ayant le souci de la qualité. Chez Zenika, il y a autant de talents en devenir que d’experts mais tous aiment partager leurs connaissances dans la convivialité et en toute transparence.

**Comment by mfrachet** [comment]
✅
